Plugin compatibility
webwinkelkeur/wordpress pull request #14
Opened 2020-11-24 14:57 UTC by TsankoBg

https://app.clubhouse.io/webwinkelkeur/story/5142/ensure-wordpress-plugin-compatibility-with-php-5-6-and-7-0
Ensure compatibility with PHP 5.6.0 and 7.0.0.
- In case PHP version is < 7.0.0 show a notice.
- Make plugin compatible with PHP 7.0.0

tested on PHP `5.6.40`, `7.0.33`, `8`
[ch5142]

2020-11-24 15:04 UTC, TsankoBg commented on trustprofile/trustprofile.php
> +if (!PhpCompatibilityCheck::isCompatible('trustprofile')) {
I sent hours dealing with this one, but this is the only scenario that works as intended.
Initially, I did
```
if (PhpCompatibilityCheck::isCompatible('trustprofile')) {
    Plugin::getInstance()->init();
}
```
However, the plugin was still installed when the version was lower than 7.0.0 and it throws an error.
The current solution, when the plugin is < 7 it does not throw an error, and it shows the plugin in installed plugins but it also shows the error `admin_notice`.

2020-11-24 17:58 UTC, apeschar requested changes

2020-11-24 17:58 UTC, apeschar commented on common/src/PhpCompatibilityCheck.php
> +                printf('<div class="%1$s"><p>%2$s</p></div>', esc_attr($class), esc_html($message));
No need for `%1$s` instead of `%s` here because the arguments are in the same order as the placeholders.

2020-11-24 17:58 UTC, apeschar commented on trustprofile/trustprofile.php
> +namespace WebwinkelKeur\WordPress;
Wrong namespace?

2020-11-24 19:21 UTC, apeschar commented
I've rebased your branch on the `next` branch, because I needed to add some fixes to the master and reordered some commits to make that possible. Before continuing your work, you should:

~~~
git checkout plugin-compatibility
git fetch
git reset --hard origin/plugin-compatibility
~~~

... so that you are working on the same commits as we have here. :)

2020-11-25 10:09 UTC, apeschar reviewed
I'll fix this last comment, and then merge.

2020-11-25 10:09 UTC, apeschar commented on common/src/PhpCompatibilityCheck.php
> +            add_action('admin_notices', function ($arguments) use ($plugin_name) {
You're not using `$arguments` here, so it should be dropped.

2020-11-25 10:13 UTC, merged