Drop deprecated class
webwinkelkeur/wordpress pull request #56
Opened 2023-10-25 07:06 UTC by TsankoBg

Replace `Requests` with `cURL`

2023-10-25 15:02 UTC, apeschar commented
The class isn't deprecated, it's only been renamed to `WpOrg\Requests\Requests`.

See: https://github.com/WordPress/WordPress/blob/master/wp-includes/class-requests.php

Three options:

1. Define `REQUESTS_SILENCE_PSR0_DEPRECATIONS` to disable the warning until we can apply option (3).
2. Use `WpOrg\Requests\Requests` if it is available (using `class_exists` or by checking the WordPress version).
3. Always use `WpOrg\Requests\Requests` and drop support for WordPress versions below 6.2.0.

Simplest option (what I'd do) is (1) and requires adding this before the `Requests` class is first used:

~~~php
if (!defined('REQUESTS_SILENCE_PSR0_DEPRECATIONS')) {
  define('REQUESTS_SILENCE_PSR0_DEPRECATIONS', true);
}
~~~

Using cURL in a WordPress plugin is not ideal since it adds another requirement. The Requests class works without cURL, so [WordPress does not require or recommend it][wp].

[wp]: https://wordpress.org/about/requirements/

2023-10-30 07:22 UTC, TsankoBg commented
I changed it based on your suggestion

2023-10-30 09:21 UTC, apeschar requested changes

2023-10-30 09:21 UTC, apeschar commented on common/src/API.php
>  use Requests;
`use` statements don't actually load anything, they just import a certain namespace.  So you can keep the `use` statements at the top as usual.

```suggestion
use Requests;

if (!defined('REQUESTS_SILENCE_PSR0_DEPRECATIONS')) {
    define('REQUESTS_SILENCE_PSR0_DEPRECATIONS', true);
}
```

2023-10-30 09:21 UTC, merged

2023-10-30 09:45 UTC, apeschar commented
Released as 3.29. (But the [plugin page][wp] still shows the old version. I guess we need to wait for their cache to clear.)

[wp]: https://wordpress.org/plugins/trustprofile/